name: Build Windows Executable

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Create .env file
      run: |
        echo "PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY || '' }}" >> .env
        echo "PINECONE_INDEX_NAME=${{ secrets.PINECONE_INDEX_NAME || '' }}" >> .env
        echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY || '' }}" >> .env
        echo "PINECONE_ENVIRONMENT=${{ secrets.PINECONE_ENVIRONMENT || '' }}" >> .env
      shell: bash
    
    - name: Verify .env file exists
      run: |
        if (Test-Path .env) { 
          Write-Host ".env file created successfully"
          Get-Content .env
        } else { 
          Write-Host ".env file not found!"
          exit 1
        }
      shell: powershell
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build executable
      run: pyinstaller main.spec
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: BibleBot-Windows
        path: dist/BibleBot.exe